version: '3'

services:
    ##########################
    ### SETUP BACKEND CONTAINER
    ##########################
    mm_backend:
        container_name: mm_backend
        restart: unless-stopped
        build: ./backend
        environment:
            - MONGO_URL=mongodb://mm_mongo:27017/report-gen
        env_file: ./backend/.env
        ports: 
            - '80:8080'
        links:
            - mm_mongo
        volumes: 
            - mmBackend_nodeModules:/user/src/app/node_modules
    ############################
    ### SETUP FRONTEND CONTAINER
    ############################
    mm_frontend:
        container_name: mm_frontend
        restart: unless-stopped
        tty: true
        build: ./frontend
        ports: 
            - '4000:3000'
        volumes: 
            - mmFrontend_nodeModules:/user/src/app/node_modules
        environment:
            - NODE_ENV=production            
    ############################
    ### SETUP DATABASE CONTAINER
    ############################
    mm_mongo:
        container_name: mm_mongo
        image: mongo
        env_file: ./backend/.env
        ports: 
            - '2717:27017'
        volumes: 
            - data:/data/db
volumes: 
    data:
    mmBackend_nodeModules:
    mmFrontend_nodeModules: