name: Deploy using AWS SSM Send-Command

on:
    push:
        branches: [master]

jobs:
    start:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: AKIAJLPQX6LYT3EJPIBA
                aws-secret-access-key: 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
                aws-region: ap-south-1
                instance-ids: i-01300efc4df826b93
                comment: Deploy the master branch
                working-directory: /home/ubuntu/stat-report-gen
            
            - name: Execute Backend commands              
              run: |
                  cd backend
                  sudo npm install
                  sudo npm install pm2 -g
                  sudo pm2 start index.js -i max --watch
                  cd ..

            - name: Execute Frontend commands              
              run: |
                  cd frontend
                  sudo npm install
                  sudo npm run build
                  cd ..
                  sudo apt install nginx
                  sudo systemctl restart nginx
