name: Deploy using AWS SSM Send-Command

on:
    push:
        branches: [master]

jobs:
    start:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Execute commands              
              run: |
                  git pull origin master
                  cd backend
                  sudo npm install
                  sudo pm2 start index.js -i max --watch
                  cd ..
                  cd frontend
                  sudo npm install
                  sudo npm run build
                  cd ..
                  sudo systemctl restart nginx              
              with:
                aws-access-key-id: AKIAJLPQX6LYT3EJPIBA
                aws-secret-access-key: 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
                aws-region: ap-south-1
                instance-ids: i-01300efc4df826b93
                comment: Deploy the master branch
                working-directory: /home/ubuntu/stat-report-gen